name: "storybook cicd dev"
description: "스토리북 빌드 파일을 S3에 업로드하고 CloudFront에 배포합니다."
inputs:
  app-name:
    description: "apps 디렉토리 내부 애플리케이션 이름"
    required: true

env:
  AWS_S3_BUCKET_NAME: monorepo-socar-storybook
  AWS_CLOUDFRONT_DISTRIBUTION_ID: E85TQX6J3744E
  HASHED_BRANCH_NAME: ""

runs:
  using: "composite"
  steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v3
      # with:
      #   repository: socar-inc/socar-actions
      #   ref: v2
      #   token: ${{ secrets.SOCAR_TECH_GITHUB_TOKEN }}
      #   path: .github/actions

    - name: Echo Red Text
      run: echo -e "\033[31m체크 아웃 완료\033[0m"

    - name: 브랜치 이름 해싱 후 환경 변수에 저장
      shell: bash
      run: |
        HASHED_BRANCH_NAME=$(echo -n '${{ github.ref_name }}' | sha256sum | cut -c1-8)
        echo "HASHED_BRANCH_NAME=$HASHED_BRANCH_NAME" >> $GITHUB_ENV

    - name: Node.js 셋업
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    # - name: ci-cdn(socar-actions) workflow를 통한 Storybook 빌드 파일 S3 업로드
    #   ues: ./.github/actions/ci-cdn
    #   with:
    #     name: ${{ env.AWS_S3_BUCKET_NAME }}
    #     aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
    #     aws-s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
    #     build-cmds: |
    #       aws s3 rm s3://${{ env.AWS_S3_BUCKET_NAME }}/${{ inputs.app-name }}/${{ env.HASHED_BRANCH_NAME }} --recursive
    #       npm install -g turbo
    #       npm install -g pnpm
    #       pnpm install --frozen-lockfile
    #       turbo run storybook:build --filter=${{ inputs.app-name }}... --output-dir=apps/${{ inputs.app-name }}/storybook-static
    #     build-cache-path: "**/node_modules"
    #     build-upload: true
    #     build-output: apps/${{ inputs.app-name }}/storybook-static
    #     build-tag: ${{ inputs.app-name }}/${{ env.HASHED_BRANCH_NAME }}

    # - name: cd-cdn(socar-actions) workflow를 통한 Storybook 빌드 파일 CF 배포
    #   uses: ./.github/actions/cd-cdn
    #   with:
    #     name: ${{ env.AWS_S3_BUCKET_NAME }}
    #     aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
    #     aws-cloudfront-update: false
    #     aws-s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
    #     aws-cloudfront-distribution-id: ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
    #     build-tag: ${{ inputs.app-name }}/${{ env.HASHED_BRANCH_NAME }}

    # - name: PR에 Storybook URL 추가
    #   uses: thollander/actions-comment-pull-request@v2
    #   with:
    #     message: |
    #       Storybook URL : https://monorepo-storybook.socar.me/${{ inputs.app-name }}/${{ env.HASHED_BRANCH_NAME }}/index.html
