name: Set CRC32 Value to Variable

on:
  push:
    branches:
      - "*"

env:
  CRC32_VALUE: ""
jobs:
  hash-ref-name:
    runs-on: ubuntu-latest
    steps:
      - name: Hash the github.ref_name
        run: |
          echo "The hash of the ref name is $(echo -n '${{ github.ref_name }}' | sha256sum | awk '{print $1}')"
