name: Set CRC32 Value to Variable

on:
  push:
    branches:
      - feature/*
env:
  REF_NAME_HASH: ""

jobs:
  set-env-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate hash and set as env
        run: |
          REF_NAME_HASH=$(echo -n '${{ github.ref_name }}' | sha256sum | cut -c1-8)
          echo "REF_NAME_HASH=$REF_NAME_HASH" >> $GITHUB_ENV

      - name: Use the Environment Variable
        uses: ./.github/actions/storybook
        with:
          ref_name_hash: ${{ env.REF_NAME_HASH }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
