name: Set CRC32 Value to Variable

on:
  push:
    branches:
      - "*"

env:
  CRC32_VALUE: ""

jobs:
  set_crc32_value:
    runs-on: ubuntu-latest
    steps:
      - name: Set CRC32 Value
        id: crc32
        run: |
          CRC32_VALUE=$(crc32 <(echo "${{ github.ref_name }}") | cut -c 1-4)
          echo "CRC32_VALUE=$CRC32_VALUE" >> $GITHUB_ENV
          echo "::set-output name=crc32_value::$CRC32_VALUE"

      - name: Use CRC32 Value
        run: |
          echo "CRC32 Value is ${{ steps.crc32.outputs.crc32_value }}"

      - name: echo CRC32 Value
        run: |
          echo "CRC32 Value is $CRC32_VALUE"

      - name: echo CRC32 Value from env
        run: |
          echo "CRC32 Value is ${{ env.CRC32_VALUE }}"
