name: Set CRC32 Value to Variable

on:
  push:
    branches:
      - "*"
jobs:
  set-env-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Generate hash and set as env
        run: |
          REF_NAME_HASH=$(echo -n '${{ github.ref_name }}' | sha256sum | cut -c1-6)
          echo "REF_NAME_HASH=${REF_NAME_HASH}" >> $GITHUB_ENV

      - name: Use the Environment Variable
        run: |
          echo "The short hash is $REF_NAME_HASH"
