name: Set CRC32 Value to Variable

on:
  push:
    branches:
      - feature/*
env:
  REF_NAME_HASH: ""

jobs:
  set-env-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use the Environment Variable
        uses: ./.github/actions/storybook
        with:
          app-name: app-main
